### ISSUE TITLE
Mixed Content Error

### ISSUE THREAD

**Issue by sethmcleod** [IonicaBizau/github-calendar#1]
On Chrome (v47.0.2526.106) I get a Mixed Content error preventing the Calendar from being loaded. 

![image](https://cloud.githubusercontent.com/assets/7340187/12148047/3e59efd6-b46a-11e5-8ebd-5f109c9a4e90.png)

This can be fixed by clicking the 'Load Unsafe Scripts' ![image](https://cloud.githubusercontent.com/assets/7340187/12148074/6b7bd7fe-b46a-11e5-879f-941ad1fdbe6b.png) button in the url bar. 

I know you mentioned the proxy (urlreq) only supports HTTP, but is there a work-around for getting this to work on secure pages?

**Comment by IonicaBizau** [comment]
Thanks for the report, @sethmcleod!

> I know you mentioned the proxy (urlreq) only supports HTTP, but is there a work-around for getting this to work on secure pages?

Probably using a proxy which supports HTTPs. When we find a good proxy (maybe YML?) we can use that as default. :thought_balloon: 

Until then you can just use the `proxy` option:

``` js
GitHubCalendar(".calendar", "your-username", {
   proxy: function (url) { return "/my-custom-proxy?" + url; }
});
```

I used YML [here](https://github.com/IonicaBizau/jQuery-cross-domain-requests), but it looks like it cannot fetch the GitHub profile pages. Not sure why (or am I wrong? I remembered I played with it a little).

**Comment by sethmcleod** [comment]
Very cool! Thanks for the quick reply

**Comment by IonicaBizau** [comment]
@sethmcleod Wait! It does support HTTPs: [`https://urlreq.appspot.com/req?method=GET&url=https%3a//github.com/ionicabizau`](https://urlreq.appspot.com/req?method=GET&url=https%3a//github.com/ionicabizau). :tada:

**Comment by sethmcleod** [comment]
Perfect, thanks for fixing this! :+1:

**Comment by IonicaBizau** [comment]
@sethmcleod It works! :lock: :key: :ship: **`1.0.1`** :+1: :tada:
