### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by guilyx** [IonicaBizau/github-calendar#100]
Hey.

Not sure if the intended behavior of your [example](https://codepen.io/anon/pen/aZmjvZeditors=1000) was what it's actually doing ( only displaying "Loading the data just for you." and not the actual calendar.

I did manage to embed it so no big deal really, just pointing this out.

**Comment by guilyx** [comment]
Fixed somehow. Closing.

**Comment by IonicaBizau** [comment]
Duplicate of #79
