### ISSUE TITLE
i want import it into my Angular 9 project, but fail. Can help me, how use it in angular.

### ISSUE THREAD

**Issue by MinhPhuPham** [IonicaBizau/github-calendar#105]
in this example: i didn't work
![image](https://user-images.githubusercontent.com/51711158/80382692-c6e7b000-88cc-11ea-8ad1-c40307f158d2.png)
---------------------------------
in my laptop, project run at localhost: so my proxy is 127.0.0.1/{port}????
please help me, code basic how to get it in angular 9 :(

**Comment by IonicaBizau** [comment]
Please ask questions on Stackoverflow.

**Comment by MinhPhuPham** [comment]
> Please ask questions on Stackoverflow.

Thank admin, i known my bug
