### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by abhishekds94** [IonicaBizau/github-calendar#106]
I am getting the wrong data from the widget.
The data I see from your screenshot in the readme is being shown instead of my actual contributions.

See the screenshot.

![image](https://user-images.githubusercontent.com/13012026/81029050-391a4080-8e49-11ea-827b-9a64bff85cc3.png)

**Comment by IonicaBizau** [comment]
Can you provide a source code?

**Comment by abhishekds94** [comment]
Sure. Please follow the link below,
https://github.com/Abhishekds94/My-Webpage/blob/master/index.html

**Comment by IonicaBizau** [comment]
This is what I see there:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/2864371/81036750-e7a19e00-8ea8-11ea-93c4-407616d71b99.png">

**Comment by abhishekds94** [comment]
This is weird but, thanks for the quick response, @IonicaBizau. I appreciate it.

This is mostly something to do with the cache. I will check it out!

**Comment by IonicaBizau** [comment]
It’s very probable that is cached. When working locally, you can disable the cache from developer tools.
