### ISSUE TITLE
Getting Failed to load resource: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by saadmk11** [IonicaBizau/github-calendar#116]
Getting ``Failed to load resource: net::ERR_NAME_NOT_RESOLVED`` error on Bloggify's API  ``https://api.bloggify.net/gh-calendar/``

**Comment by sarthakgoenka** [comment]
I've got the same error.

**Comment by IonicaBizau** [comment]
Thanks for this. I connected `bloggify.net` to Cloudflare and I'm struggling to setup the `api` subdomain again.

Any advice is appreciated.

**Comment by IonicaBizau** [comment]
I think it should be proxied now.

I added an `A` record in the Cloudflare settings, pointing to our server.

**Comment by saadmk11** [comment]
> I think it should be proxied now.
> 
> I added an `A` record in the Cloudflare settings, pointing to our server.

Yes its working thanks for the quick fix. :)

**Comment by IonicaBizau** [comment]
Glad to hear. It should load faster as it is proxied by Cloudflare now and some caching may be there too.
