### ISSUE TITLE
Tooltips not working?

### ISSUE THREAD

**Issue by 1990eam** [IonicaBizau/github-calendar#118]
I got the calendar working and am passing the following arguments:

```
new GitHubCalendar(".calendar", "1990eam", {

    responsive: true,
    tooltips: true
});

```
The calendar is responsive but the tooltips don't work.

Any suggestions? There are no errors in the console.

**Comment by IonicaBizau** [comment]
Can you link a live demo?

**Comment by 1990eam** [comment]
> Can you link a live demo?

Hello. Yes of course, [here](https://1990eam.github.io/profile/) .

Thanks.

**Comment by IonicaBizau** [comment]
I think you simply use an old version of the library. Do not use `cdn.rawgit.com` anymore because it is deprecated.

Use this url instead: `https://unpkg.com/github-calendar@latest/dist/github-calendar.min.js`.

**Comment by 1990eam** [comment]
Thanks, that worked.
