### ISSUE TITLE
Empty space exists

### ISSUE THREAD

**Issue by k3nsuk3** [IonicaBizau/github-calendar#12]
GitHub update interface of the contributions calendar on May 20, 2016. As part of this update, code streaks are no longer featured on the contributions calendar.
[https://github.com/blog/2173-more-contributions-on-your-profile](https://github.com/blog/2173-more-contributions-on-your-profile)

But some codes related to code streaks are still existing in this project. Due to this, empty space is shown.

![github-calendar_screenshot](https://cloud.githubusercontent.com/assets/4849408/15685842/9996c4c6-27a8-11e6-8b5b-fc663de42e70.jpg)

OS: OSX El Capitan 10.11.5,   Browser: Safari 9.1.1

**Comment by IonicaBizau** [comment]
Obviously yes. I'm not sure which would be the best here: should we compute the longest streak, total contributions and current streak like before? It's actually possible and not that hard.

The simple way is just to update the `min-height` value.

**Comment by IonicaBizau** [comment]
What do you think? Maybe having an option to enable/disable the global stats (total, longest and current streaks) would not be bad. 💭

**Comment by k3nsuk3** [comment]
I think that having an option to enable/disable the global stats is best to resolve this issue.

But I'm sorry I don't know how to compute global stats.😢

**Comment by IonicaBizau** [comment]
I have a module to parse the HTML: https://github.com/IonicaBizau/github-calendar-parser
From [`git-stats`](https://github.com/ionicabizau/git-stats) I'm going to split another module which will compute the stats: because it's the same code.

🚀

**Comment by IonicaBizau** [comment]
@trileg Actually, that module parses the total, longest and current streak, already ✨

**Comment by IonicaBizau** [comment]
🚢 **`1.1.x`** 🎉 Fixed via #14.
