### ISSUE TITLE
Github calendar not working

### ISSUE THREAD

**Issue by Ariel-MN** [IonicaBizau/github-calendar#120]
Github calendar has unexpectedly stopped working since yesterday, look at [montesariel.com](https://montesariel.com). How much to fix it? Can you add the option to download it as a plugin? I've been using the URLs provided in your readme file and they still active.

**Comment by IonicaBizau** [comment]
I think GitHub changed the way they render the colors:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/2864371/97576454-dcae6d00-19f6-11eb-834f-c41dce5a6737.png">


I don't have time to work on this right now, but contributions are more than welcome! ❇️

**Comment by Ariel-MN** [comment]
Not only that, number of contributions and streaks doesn't show either, I believe the hole think is broken.

**Comment by arjunskumar** [comment]
any solutions?

**Comment by perpetualCreations** [comment]
Weird, the API returns the total number of contributions, however nothing on streaks.
Did it always work like that?
Also, how did colors get parsed previously?

Full disclosure, I have no qualifications in JS.

**Comment by Doohwancho** [comment]
maybe it has something to do with halloween updates. github used other module to change color from green to pumkin for halloween day.
if my guess is correct, they would return it to original state when halloween is over.

**Comment by Ariel-MN** [comment]
@Doohwancho if it's that, it would be nice to implement a solution for prevent this scenario each year, it's ugly to have things broken on your website and I like this tool. It's a shame that I don't have the time for this right now.
I would expect the GitHub team to be more consistent with their code to avoid these kinds of issues.

**Comment by imSrbh** [comment]
> maybe it has something to do with halloween updates. github used other module to change color from green to pumkin for halloween day.
> if my guess is correct, they would return it to original state when halloween is over.

weird..Yeah It's just because of Halloween update

**Comment by perpetualCreations** [comment]
Glad to see it isn't anything serious though. 
Best of luck to any JS dev willing to implement a fix to prevent this from happening next year.

**Comment by IonicaBizau** [comment]
Just a quick update: there are two things we have to fix here:

 - the parser: https://github.com/IonicaBizau/github-calendar-parser
 - the CSS to show the right colors

**Comment by Cipher-Coder** [comment]
Adding the CSS Vars to the stylesheet will get the days to render. Something like:

```
:root {
  --color-calendar-graph-day-bg: #dddbdb;
  --color-calendar-graph-day-L1-bg: #39dd34;
  --color-calendar-graph-day-L2-bg: #45a045;
  --color-calendar-graph-day-L3-bg: #047526;
  --color-calendar-graph-day-L4-bg: #0a4208;
}
```
However I am still looking at the streak and total counts.

**Comment by IonicaBizau** [comment]
I fixed the parser in https://github.com/IonicaBizau/github-calendar-parser/pull/17.

I am working on this.

**Comment by lopezdp** [comment]
@IonicaBizau thank you!

**Comment by Ahabibullah** [comment]
there is a workaround @yeuk0 mention it [issue #620](https://github.com/joelshepherd/tabliss/issues/620)
