### ISSUE TITLE
URL Down

### ISSUE THREAD

**Issue by Ariel-MN** [IonicaBizau/github-calendar#121]
Both urls are down in your your pencode example:
https://cdn.rawgit.com/IonicaBizau/github-calendar/master/dist/github-calendar.min.js
https://cdn.rawgit.com/IonicaBizau/github-calendar/master/dist/github-calendar.css

**Comment by IonicaBizau** [comment]
https://cdnjs.com/libraries/github-calendar 

We will have to use the cdnjs urls instead...
