### ISSUE TITLE
The example shows only black boxes

### ISSUE THREAD

**Issue by vgvassilev** [IonicaBizau/github-calendar#122]
I have the same issue that can be seen in the example: https://bloggify.github.io/github-calendar/example

How we can fix this?

**Comment by shijiezhou1** [comment]
I think this repo is no longer maintains by this guy. We need to find something else.

**Comment by moselhy** [comment]
#120

**Comment by IonicaBizau** [comment]
Duplicate of #120. Contributions are welcome to fix this.
