### ISSUE TITLE
Streak & Contributions not working again

### ISSUE THREAD

**Issue by Cipher-Coder** [IonicaBizau/github-calendar#129]
Just wanted to let you know that the GitHub Streaks and Contributions are not working again. I rolled my version back to 2.1.1 because that is just what version I had on this computer since I am not at work, and it works. Im sure a more recent version may work too. To be honest I never really looked into what happened just a few weeks ago, and I am not sure if this is going to keep happening?

**Comment by NoahPeeters** [comment]
I have the same issue. I rolled back to version `2.2.3`. When I try to use version `2.2.4`, streak and contributions just display 0.

**Comment by Cipher-Coder** [comment]
You can probably close this now. It started working again. Any idea what keeps happening? Or if it is going to continue to keep happening?

**Comment by NoahPeeters** [comment]
For me, it's working again as well. If the error should appear again (and I notice it), I will try to investigate the issue.

**Comment by IonicaBizau** [comment]
It should be because of the changes in the GitHub markup. It seems to work now. :sparkle:
