### ISSUE TITLE
Tooltips are not working (2.2.7)

### ISSUE THREAD

**Issue by jxmot** [IonicaBizau/github-calendar#136]
Hello,

I'm trying to get tooltips to work. I've looked through the PRs and issues and there appears to have been a "fix" made but that was in 2020.

I've examined the live demo code, and it is enabling tooltips but they do not work. I have also downloaded the latest (2.2.7) from the repo and it isn't working either.

To see this error, just go to the project demo page. So far it has not worked on Chrome, FireFox, and Opera.

Thanks!

**Comment by secondl1ght** [comment]
I have the same issue, I have enabled tooltips but nothing appears on mouse hover.

**Comment by IonicaBizau** [comment]
Hmm, they seem broken on the demo page too... Contributions are welcome!

**Comment by pengfeiw** [comment]
I create a pull request to fix this bug.

**Comment by secondl1ght** [comment]
Still not working for me, will it take a little bit of time to start working?

**Comment by pengfeiw** [comment]
Do you set the `tooltips: true` ? @secondl1ght

**Comment by secondl1ght** [comment]
Yes I had that enabled the whole time, I just left it like that even though they were not working. I refreshed my page, do I need to do anything else?

**Comment by pengfeiw** [comment]
The [example](https://bloggify.github.io/github-calendar/example/) has tooltips now, check you has updated the github-calendar package in your project. @secondl1ght

**Comment by secondl1ght** [comment]
Is it possible to have tooltips with just vanilla JS? I added the ```script``` tags but did not install anything with yarn or npm.

**Comment by pengfeiw** [comment]
The content of [script](https://unpkg.com/github-calendar@2.2.8/dist/github-calendar.min.js) is not the newest.

**Comment by secondl1ght** [comment]
So we need to update that or I can just paste the whole script in my code and make the change you just PR'ed?

**Comment by secondl1ght** [comment]
Update: Yep that worked, I just put the script right in my project and then updated it with the fix you just made in your PR. Thanks!

**Comment by secondl1ght** [comment]
One more thing if you are interested in doing more, when you hover of the 'Less More' boxes a tooltip appears with ```null``` but it should probably just not appear at all for those boxes. @pengfeiw

**Comment by pengfeiw** [comment]
Thanks for point that out. I'll fix it later.

**Comment by pengfeiw** [comment]
I have make a new pr to fix it. @secondl1ght
