### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by justoverclockl** [IonicaBizau/github-calendar#146]
At smaller resolution is not responsive
![Immagine 2022-02-18 155805](https://user-images.githubusercontent.com/79002016/154707105-db7842ee-65ec-4c85-9fa4-4c8d039bd7c2.png)

**Comment by darshikaguptaa** [comment]
Can you please assign this issue to me?

**Comment by IonicaBizau** [comment]
This would be amazing. Just simply open a PR to fix this. Thanks!
