### ISSUE TITLE
Can't I see a graph that reflects the change immediately?

### ISSUE THREAD

**Issue by dooli1971039** [IonicaBizau/github-calendar#156]
![image](https://user-images.githubusercontent.com/70802352/204106287-69497ec3-351e-4eb9-8359-7c96f73ccc1b.png)
How can I get not UTC time data?
in https://github.com/users/dooli1971039/contributions, it shows me the latest data. ( not UTC time)
![image](https://user-images.githubusercontent.com/70802352/204106348-43f097da-78f4-40b8-97bc-8f27ef74b3a4.png)
I want to eliminate the nine-hour difference.

**Comment by dooli1971039** [comment]
ㅇㅎㄹㅇㄹㅇ

**Comment by IonicaBizau** [comment]
Duplicate of #138
