### ISSUE TITLE
Hello, Calendar Stopped Displaying

### ISSUE THREAD

**Issue by HernanMorel** [IonicaBizau/github-calendar#170]
I've been using this package for about 2 months, today I noticed that the calendar is no longer visible out of nowhere. No changes made on my end.

This is the devTools error `TypeError: Cannot read properties of null (reading 'getAttribute')`

This is my component

```
import React, { useEffect } from 'react';
import GitHubCalendar from 'github-calendar';

function GHCalendar() {
  const myRef = React.useRef(null);

  useEffect(() => {
    if (myRef.current) {
      GitHubCalendar(myRef.current, 'HernanMorel', {
        responsive: true,
        cache: 5,
      });
    }
  }, []);

  return <div className="calendar" ref={myRef} />;
}

export default GHCalendar;

```

**Comment by shivam-bit** [comment]
@HernanMorel were you able to find a fix for this? i am facing same issue.

**Comment by HernanMorel** [comment]
I wasn't unfortunately. I resorted to another library to display the same info. I can do some digging to see exactly which one I used if you need it still.
