### ISSUE TITLE
How do I deploy the API myself

### ISSUE THREAD

**Issue by Robert-Stackflow** [IonicaBizau/github-calendar#177]
- I really like your job, it's great!
- I noticed that the interface used by the js script is api.bloggify.net. How should I deploy my own API interface?
- I noticed that in your API, the return result is directly the content of the include-fragment component used in the GitHub official website, rather than the entire HTML document. How is this done?

**Comment by IonicaBizau** [comment]
That is just a proxy for convenience. It's a great idea to add it in the repository actually! 👍

**Comment by Robert-Stackflow** [comment]
Thank you and I hope you can add the code to get the html page in the repository! 👍👍

**Comment by IonicaBizau** [comment]
https://github.com/Bloggify/github-calendar/tree/gh-pages/proxy-self-hosted

Here you can check out the PHP code for the proxy. 😁
