### ISSUE TITLE
TypeError: f.querySelector(...) is null

### ISSUE THREAD

**Issue by miroslavvidovic** [IonicaBizau/github-calendar#23]
The GitHub calendar is not loading and I have the following error:

`TypeError: f.querySelector(...) is null`

in the github-calendar.min.js file. When I  unminify the file it shows the error is on line 56.
I think the problem is with the querySelector() function not matching any CSS selector for the class .left.text-muted:

`if (f.querySelector(".left.text-muted").innerHTML = c.summary_text, f.querySelector("include-fragment")) setTimeout(l, 500);`

**Comment by IonicaBizau** [comment]
Whoups! Indeed an issue!

Can you take a look at it? I'm more focused on other projects these days, but I'm happy to accept contributions.

In this case, it's probably just a matter of query selectors.
