### ISSUE TITLE
Request: Unminified dist file for debugging

### ISSUE THREAD

**Issue by shellscape** [IonicaBizau/github-calendar#26]
I'd like to request an unminified version of the script in the `dist` directory for use with the rawgit cdn.

**Comment by IonicaBizau** [comment]
Just use `browserify lib/index.js -s GitHubCalendar -o dist/gh-cal.js`.

That's what dist-it does + babelify + minify. 😁

**Comment by shellscape** [comment]
Why not add that as an additional script in package.json? (trying to help push this towards a more user-friendly project)

**Comment by IonicaBizau** [comment]
@shellscape It should be a `dist-it` option, probably. 😄

**Comment by shellscape** [comment]
sooo you don't want to make this more user-friendly? ok, I guess.

**Comment by IonicaBizau** [comment]
This is dist-it related and it's about the same problem across repositories, so, let's handle it in `dist-it`.

/cc https://github.com/IonicaBizau/dist-it/issues/9
