### ISSUE TITLE
dist-it not in devDependencies

### ISSUE THREAD

**Issue by shellscape** [IonicaBizau/github-calendar#27]
Kind of key to have this listed in deps since it's the sole component responsible for releasing. I'd also highly recommend leveraging `david` to keep your deps up to date.

**Comment by IonicaBizau** [comment]
This is/[should be](https://github.com/IonicaBizau/dotfiles/issues/35) happening automagically when I publish new versions.

`david` looks neat! 👍

**Comment by shellscape** [comment]
Why did you close this issue? Your response didn't address it. `dist-it` is a requirement in order to build the script locally. If you're not using it as a direct devDep, then it should be listed in the documentation as a global requirement in order to build.
