### ISSUE TITLE
The given example is not loading

### ISSUE THREAD

**Issue by xdev00** [IonicaBizau/github-calendar#29]
The provided link is not loading. Please help. Thank you.

**Comment by IonicaBizau** [comment]
Hmm, can you just refresh the page? Maybe it's slow due to my active graph. 😁

**Comment by xdev00** [comment]
I've already did. I tried it in sample project too, same thing happens.

**Comment by IonicaBizau** [comment]
Can you take a look in the console and check for errors? What browser are you using?

**Comment by xdev00** [comment]
I use chrome. It says GithubCalendar not defined. And the cdn is 404.

**Comment by IonicaBizau** [comment]
Are you sure you're looking at this page? If the cdn link is broken, then that's why.

But there's no cdn link here: http://ionicabizau.github.io/github-calendar/example/

**Comment by xdev00** [comment]
Oh I see. Heres the link I've used. http://codepen.io/anon/pen/aZmjvZ?editors=1000. Thats what on the documentation. Anyways thanks for the prompt response. It helps me a lot.

**Comment by IonicaBizau** [comment]
@kevin1193 Whoups! Can you fix that for me?

**Comment by xdev00** [comment]
Yeah sure. I will. Thank you.

**Comment by xdev00** [comment]
I cant save using the same link in codepen. It works fine now in this link 
http://codepen.io/kevin123456/pen/JRjPpE?editors=1000

Thanks a lot for your help.

**Comment by tiborsimon** [comment]
In Safari there is still a missing dependency. I've added fetch() through a cdn.
http://codepen.io/tiborsimon/pen/mrZeVB

Works in Safari, Chrome and in Firefox.

**Comment by IonicaBizau** [comment]
@tiborsimon Maybe it would make sense to bundle the polyfill too.

**Comment by marcodearaujo** [comment]
Didn't work for me too, I believe could be SSL problem in https://urlreq.appspot.com/ because it works when I change to http

**Comment by IonicaBizau** [comment]
@marcoaraujojunior Hmm... `urlreq` should work with `https`. Can you add information about platform, operating system, browser etc?

Maybe  also check the developer tools errors?

**Comment by marcodearaujo** [comment]
System: Linux server21.hostinger.com.br 3.2.55-grsec #1 SMP Thu Mar 27 12:58:18 EDT 2014 x86_64
Browser: Chrome version 55.0.2883.75 (64-bit)
![error](https://cloud.githubusercontent.com/assets/4330991/21816033/c0a37530-d745-11e6-9f44-dfa0fad2b886.png)

**Comment by IonicaBizau** [comment]
Hmm, so timeout... Interesting.

**Comment by IonicaBizau** [comment]
Is this still a problem?
