### ISSUE TITLE
Query selector for calendar needs to be changed

### ISSUE THREAD

**Issue by miroslavvidovic** [IonicaBizau/github-calendar#30]
GitHub had again some style changes and the github-calendar widget won't load:

Div containing the calendar graph has changed from 
`div id="contributions-calendar"` 
to
`div class="js-contribution-graph"`

**Comment by IonicaBizau** [comment]
Oh, thanks for the note. Contributions are welcome!

**Comment by IonicaBizau** [comment]
Fixed via #31 :tada: Thanks!
