### ISSUE TITLE
Example of using Object options

### ISSUE THREAD

**Issue by TMorville** [IonicaBizau/github-calendar#40]
Hi Ionica. I asked you on stackoverflow about adding your github-calendar to Jekyll. I am writing up a guide now. Before I do so, can you perhaps give a few examples of how to use the "options object" in the GitHubCalendar (main.js) function? I think that a lot of people using Jekyll are using a theme, and e.g. the theme I am using squeezes the information in the calendar slightly. So it would be nice to be able to see a minimal representation. 

It does not seem to work when calling <options "global_stats=false"> in GitHubCalendar.  Perhaps I am doing it wrong? 

Thanks!

**Comment by IonicaBizau** [comment]
The `options` argument is optional. In case you want to change the defaults here's how:

```html
<script>
    GitHubCalendar(".calendar", "your-username", {
        global_stats: false
    });
</script>
```

**Comment by Priyansh2** [comment]
@IonicaBizau it is good if you add this too in your repo's documentation about using options . It will help others a lot ..they don't have to come to the issue page to solve their problems .

**Comment by IonicaBizau** [comment]
I agree! We should edit [those lines](https://github.com/IonicaBizau/github-calendar/blob/06dcb6fbaf814c92d5c8560e8863bf3c83fab08b/package.json#L63-L65). Contributions are welcome!
