### ISSUE TITLE
How to add a minimal version of the calendar using Jekyll

### ISSUE THREAD

**Issue by TMorville** [IonicaBizau/github-calendar#41]
1) Make a .html file with the following content (I have it as my index) and save as index.html

```
---
layout: default
---

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>GitHub Calendar</title>
        <link rel="stylesheet" href="assets/dist/style.css">
    </head>
    <body>
        <div class="bag fixed">
            <div class="calendar">
                <img src="https://assets-cdn.github.com/images/spinners/octocat-spinner-128.gif" class="spinner"/>
            </div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/3.0.2/es6-promise.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/0.10.1/fetch.min.js"></script>
            <script src="assets/dist/github-calendar.min.js"></script>
            <script src="assets/dist/main.js"></script>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.0.0/highlight.min.js"></script>
        <script>hljs.highlightBlock(document.querySelector("pre"))</script>
    </body>
</html>
```

2) Under a subfolder (e.g. assets) make a new folder (dist) and add github-calendar.css, github-calendar.min.js, main.js and style.css from @IonicaBizau repository. Change the links in your index.html file accordingly. E.g.  `<script src="assets/dist/main.js"></script>. `

This (and a bit of tweaking the main.js and style.css) will generate the result as seen on [my site](https://tmorville.github.io/).

**Comment by IonicaBizau** [comment]
Nice! :+1: We can create a Wiki probably and include things like this there. For now I'll leave this opened until I'll create a Wiki page.

**Comment by IonicaBizau** [comment]
Feel free to create a PR with that.
