### ISSUE TITLE
Can not work for chrome now(unsafe https certificate)

### ISSUE THREAD

**Issue by ecmadao** [IonicaBizau/github-calendar#46]
This url, `https://urlreq.appspot.com/req?method=GET&url=`, was marked as unsafe by chrome cause it https certificate, so this extension can not work anymore on chrome browser (but still worked well on safari).

**Comment by ecmadao** [comment]
Sorry, it seems I should make a new issue for https://github.com/izuzak/urlreq

Anyway, many thanks for your extension! It worked well on my [website](https://hacknical.com?locale=en)

**Comment by ecmadao** [comment]
https://github.com/izuzak/urlreq/issues/5

**Comment by IonicaBizau** [comment]
It works for me. Chrome, latest version, macOS.
