### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by calumk** [IonicaBizau/github-calendar#51]
I don't think the responsive layout is actually implemented?

**Comment by IonicaBizau** [comment]
Have you tried passing `responsive: true` in the options?

**Comment by a-y-u-s-h** [comment]
I tried, it's not working.

**Comment by IonicaBizau** [comment]
Can you create a jsfiddle or online demo?

**Comment by jma26** [comment]
Yep, it's not working for me too. There are multiple opened issues in regarding responsive layout implementation
