### ISSUE TITLE
Individual Repository Stats

### ISSUE THREAD

**Issue by jazrobinson** [IonicaBizau/github-calendar#52]
I just wanted to start by saying your script is awesome and thank you for sharing your work with the world.  I wanted to use your script for showing details of repositories instead of based on a person.  Is it possible to use your script so I can display the stats on just one of my public repositories instead of all of my activity on all repositories?  I hope that makes sense.

Ideally you would pass your repository url
example: IonicaBizau/github-calendar 
Would display the activity calendar on only that repository.

Again wonderful script =)

**Comment by IonicaBizau** [comment]
A similar chart can be used and data provided by the GitHub api: https://developer.github.com/v3/repos/statistics/#get-the-last-year-of-commit-activity-data

However, currently this is not supported in the GitHub Calendar project which only requests the information in HTML-ish format directly form GitHub (using a proxy).

The chart type is called calendar heatmap (e.g. https://github.com/DKirwan/calendar-heatmap)
To access the GitHub API you can use this minimal library: https://github.com/IonicaBizau/gh.js
(or use `fetch` or the `d3` methods)

**Comment by IonicaBizau** [comment]
Related:

 - http://ionicabizau.github.io/github-profile-languages/?user=jazrobinson
 - http://ionicabizau.github.io/github-profile-languages/?user=jazrobinson%252Fhello-world
