### ISSUE TITLE
Stats displayed offset to left

### ISSUE THREAD

**Issue by jmccormac01** [IonicaBizau/github-calendar#53]
Hi,
I've been using your nice calendar for a while but I noticed recently that the stats at the bottom are displayed off set to the left. See image attached. You can see my webpage here: jamesjmccormac.com. Do you have any ideas why this happens? I get the same in Safari and Firefox. 

Cheers,
James

![screenshot 2018-03-28 17 15 44](https://user-images.githubusercontent.com/1912007/38042295-e80aa23e-32ab-11e8-94e7-a45930f177a1.png)

**Comment by IonicaBizau** [comment]
A very unscientific assumption is that flex box doesn’t seem to work properly... but I can’t debug it right now.

**Comment by jmccormac01** [comment]
No worries, I've looked at flex before, I'll see if I can figure it out. Bootstrap columns would work well too I think.
