### ISSUE TITLE
Adding tooltip hover event 

### ISSUE THREAD

**Issue by Rembrandtsx** [IonicaBizau/github-calendar#55]
I would like to see a fully responsive tooltip for each day just like it does github where it shows you the amount of commits per day.

**Comment by IonicaBizau** [comment]
Contributions are welcome in this direction.

**Comment by RathiRohit** [comment]
Hi @IonicaBizau If this is still open for contribution, I can submit a PR for this.

**Comment by IonicaBizau** [comment]
Sure, that would be amazing! ✨
