### ISSUE TITLE
Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by kjin1** [IonicaBizau/github-calendar#57]
<img width="846" alt="2018-08-23 11 23 20" src="https://user-images.githubusercontent.com/3953011/44501161-022ce700-a6c7-11e8-8af7-37e6078044b2.png">

github-calendar.js worked well until yesterday, but I have some issue with github-calendar.js today. console said “TypeError: Cannot read property ‘querySelector’ of null”. I tested it with chrome and safari.

**Comment by wit03** [comment]
I recommend you to format the code layout for github-calendar.min.js. I found problem at line 53 and 82 but I have no idea to fix it.

**Comment by Rembrandtsx** [comment]
i've got the same problem with the plugin i think is somthing about the server or something like that.

**Comment by IonicaBizau** [comment]
Should be fine now! 👍 Fixed via #58
