### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by ReyRod** [IonicaBizau/github-calendar#6]
Could you make a gitlab version?

**Comment by IonicaBizau** [comment]
I'm not familiar with Gitlab. Do they expose similar contributions stats? 💭

**Comment by ReyRod** [comment]
Yes, you should check it out, it offers private repositories for free and
have many features and integrations available
El may 5, 2016 2:12 PM, "Ionică Bizău" notifications@github.com escribió:

I'm not familiar with Gitlab. Do they expose similar contributions stats? 💭

**Comment by IonicaBizau** [comment]
This project is really related to GitHub.com. Maybe it could be another project doing that, but this module should only load the GitHub calendar.

If you build/find a project like that, we can link it in the README.md file. :memo:

**Comment by anibal-aguila** [comment]
Hi @IonicaBizau I don't found any nice alternative for GitLab, do you know how I can use github-calendar with GitLab contribution calendar?

Thanks in advance,

**Comment by pktiuk** [comment]
@anibal-aguila 
I think you should watch this issue: https://gitlab.com/gitlab-org/gitlab/-/issues/29733

**Comment by IonicaBizau** [comment]
I am not very familiar with GitLab... Does the API provide a similar stats functionality?

You can always override the `getCalendar` method and return the body you want to set in the HTML.
