### ISSUE TITLE
Responsive Function isn't working

### ISSUE THREAD

**Issue by wit03** [IonicaBizau/github-calendar#61]
I've tried 
`GitHubCalendar(".calendar", "wit03", {
    responsive: true
});`
it still doesn't work

**Comment by iphysresearch** [comment]
I think you need use the new `github-calendar.min.js`.

You can check the source code of https://ionicabizau.github.io/github-calendar/example/   ....

**Comment by IonicaBizau** [comment]
Duplicate of #51
