### ISSUE TITLE
how to integrate this with vue?

### ISSUE THREAD

**Issue by ghost** [IonicaBizau/github-calendar#62]
hi,  
I'm trying to integrate this with my Vue project. but it doesn't work.

main.js
`
import GitHubCalendar from "github-calendar"
import "github-calendar/dist/github-calendar-responsive.css"
Vue.use(GitHubCalendar(".calendar", "SaadKhanMalik"))
`

my console spits out 
`
index.js?02ed:99 TypeError: Cannot set property 'innerHTML' of null
   at eval (index.js?02ed:96)
(anonymous) @ index.js?02ed:99
`
would really love to intergrate this.

thanks

**Comment by IonicaBizau** [comment]
I haven't worked with vue... but I'm cc'ing @egoist and @ghitab here. Maybe they have some ideas.

**Comment by egoist** [comment]
Why did you even try to call `Vue.use(GitHubCalendar(".calendar", "SaadKhanMalik"))` 😂 It's not a Vue plugin.

To use it in a Vue component, you can call `GitHubCalendar(element, username)` in the component's `mounted` hook.

**Comment by OziOcb** [comment]
First, install the package:
```
# Using npm
npm install --save github-calendar

# Using yarn
yarn add github-calendar
```

Then, in .vue file: (I created a separate component for this)
```
<template>
  <div class="calendar">
    <!-- Loading stuff -->
    Loading the data just for you.
  </div>
</template>

<script>
import GitHubCalendar from "github-calendar"

export default {
  mounted() {
    GitHubCalendar(".calendar", "YOUR_USER_NAME", {
      responsive: true
    })
  }
}
</script>
```

Do not forget to import the calendar's styles
