### ISSUE TITLE
c.querySelector issue

### ISSUE THREAD

**Issue by vvzen** [IonicaBizau/github-calendar#63]
The snippet won't show.
Line error:  github-calendar.min.js:1:1667

`TypeError: null is not an object (evaluating 'c.querySelector')`

Tested in Safari and Firefox

**Comment by saiqulhaq** [comment]
this issue already fixed by https://github.com/IonicaBizau/github-calendar/pull/58

but the package maintaner haven't rebuild it yet

you may use my forked version, but the source is not minified
https://github.com/saiqulhaq/github-calendar

```
<link rel="stylesheet" href="https://cdn.rawgit.com/saiqulhaq/github-calendar/gh-pages/dist/github-calendar.css" />
<script src="https://cdn.rawgit.com/saiqulhaq/github-calendar/gh-pages/dist/github-calendar.min.js"
```
