### ISSUE TITLE
User contribution chart not hidden in responsive version of CSS

### ISSUE THREAD

**Issue by eternal-flame-AD** [IonicaBizau/github-calendar#68]
https://github.com/IonicaBizau/github-calendar/blob/aaf8c9c4dcc24287538908f9b2579a51bf85194f/dist/github-calendar.css#L125-L127

I think this three lines should also be added to `github-calendar-responsive.css` because otherwise the contribution chart would display badly using the responsive stylesheet.

**Comment by JS-goose** [comment]
I agree with this.  I want to use the responsive CSS but it's only responsive to a certain point and then the chart spills over.

**Comment by IonicaBizau** [comment]
Fixed in the latest release.
