### ISSUE TITLE
Undocumented dev dependencies

### ISSUE THREAD

**Issue by palmerev** [IonicaBizau/github-calendar#7]
I tried running `npm run release`, but `uglify-js` was throwing a syntax error. I realized that I also needed `babel-preset-es2015` for it to work. Then adding the preset in the release command works:
`browserify lib/index.js -o dist/github-calendar.min.js -s GitHubCalendar && babel --presets es2015 dist/github-calendar.min.js | uglifyjs -c -m -o dist/github-calendar.min.js`

Or, adding babel config to package.json:

```
"babel": {
    "presets": ["es2015"]
  }
```

I think it would be a good idea to have everything that the release command uses be declared in devDependencies in the package.json, something like:

```
"devDependencies": {
    "babel-cli": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "browserify": "^13.0.0",
    "uglify-js": "^2.6.2"
  }
```

There could also be a note in the `CONTRIBUTING.md` about this. :memo:

**Comment by IonicaBizau** [comment]
@palmerev We should use [`dist-it`](https://github.com/IonicaBizau/dist-it) instead. 😁  Thanks for bringing this in attention!
