### ISSUE TITLE
How to edit the styling definition in elements ?

### ISSUE THREAD

**Issue by GohEeEn** [IonicaBizau/github-calendar#75]
Hi, I am building a GitHub page for myself with embedding this calendar into my source code, and I am customizing the styling definitions for the calendar elements.

The image bellow shows what it actually looks like in browser developing tool,
![image](https://user-images.githubusercontent.com/34720382/58215867-d2614d00-7cf3-11e9-9437-35bf0a1d9b46.png)

while this is the source code given to embed this GitHub calendar into the webpage, 
![image](https://user-images.githubusercontent.com/34720382/58215924-06d50900-7cf4-11e9-9732-a08ef940137a.png)

Does anyone know how can I find the source code in the black rectangle, so I can redefine the styling definition for those elements ?
![image](https://user-images.githubusercontent.com/34720382/58216161-1bfe6780-7cf5-11e9-9c02-74d54adb0342.png)
I know there are some of the styling attribute declaration can be found in the [JavaScript code](https://unpkg.com/github-calendar@latest/dist/github-calendar.min.js), while it is only partial are found by me. For example, how can I remove the styling attribute `mx-3` in `<div class="contrib-footer ...">` element?

**Comment by IonicaBizau** [comment]
Just use regular JavaScript to manipulate the code after the rendering step.
