### ISSUE TITLE
Link to the example page

### ISSUE THREAD

**Issue by rodrigograca31** [IonicaBizau/github-calendar#84]
Hi!

I was just in class and an issue came up about this lib but we couldnt find this example page anywhere: http://ionicabizau.github.io/github-calendar/example/

So, Im proposing that it should be linked in the README.md so that we can quickly reach it.

After `Installation` and before `Documentation` ?
I can send a PR right away.

Purposed change:

## Example:
[You can find an example here](http://ionicabizau.github.io/github-calendar/example/)

**Comment by IonicaBizau** [comment]
That would be great! 😄

**Comment by rodrigograca31** [comment]
there you go, with an image and all :smile:
