### ISSUE TITLE
Running the script changes the tab .ico to the github logo

### ISSUE THREAD

**Issue by rudikershaw** [IonicaBizau/github-calendar#86]
The summary more or less says it all. I am using a code snippet I saw you provide against a Stackoverflow answer which I will show below;

```
<script src="https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.css"/>
<div class="calendar">Loading Github contributions.</div>
<script> new GitHubCalendar(".calendar", "rudikershaw");</script>
```

After the script finishes running on the page, the page tab ico is swapped out for the github logo. I'm going to look into this, but I am not holding up hope of finding a solution myself.

Browser: Firefox 70.0.1 (64-bit) for Ubuntu canonical - 1.0
OS: Ubuntu 18.04

**Comment by IonicaBizau** [comment]
Probably this got fixed after the last optimizations... Can you double check that?

**Comment by rudikershaw** [comment]
Appears to be working as intended now. Thank you.
