### ISSUE TITLE
"Contributions in the last year" with inaccurate start date

### ISSUE THREAD

**Issue by snowztail** [IonicaBizau/github-calendar#87]
It shows Dec 1, 2018 – Dec 1, 2019 instead of Dec 2, 2018 – Dec 1, 2019.

**Comment by snowztail** [comment]
[#88 ](https://github.com/IonicaBizau/github-calendar/pull/88) gives a possible fix.

**Comment by IonicaBizau** [comment]
Thanks, @SnowzTail :cake:

🚀 1.3.4.
