### ISSUE TITLE
Rectangle Colors

### ISSUE THREAD

**Issue by caleblallen** [IonicaBizau/github-calendar#91]
Hi All,

I'd like to add an option field for changing the rectangle colors. 

`GitHubCalendar(domObject, uName, 
     { summary_text: 'blah',
       global_stats: true,
       responsive: true,
       base_color: '#FF5733' });`

Base color would correspond to the current #239a3b slot (2nd to last). It would overwrite the last three values, leaving the base gray (#ebedf0) in place. Other colors would be calculated from the base color (darker, lighter).

The legend would also be changed to correspond.

**Comment by IonicaBizau** [comment]
This is already possible via CSS, like explained [here](https://github.com/IonicaBizau/github-calendar/issues/48).

Perhaps we should update the docs regarding this.

**Comment by caleblallen** [comment]
Hi @IonicaBizau, sorry, yes it had been in documentation I think I might not have bothered you with it :)
