### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by 1sdc0d3r** [IonicaBizau/github-calendar#94]
It doesn't load in the script. It keeps the "Loading the data just for you.". This is on the codePen as well. It doesn't render properly.

**Comment by IonicaBizau** [comment]
Can you please check out the errors in the console?

**Comment by 1sdc0d3r** [comment]
So sorry, I didn't expect a response back as quickly as you did. Here is a screenshot of the error. This is with it implemented in my application.

<img width="1004" alt="Screen Shot 2020-01-16 at 11 10 04 AM" src="https://user-images.githubusercontent.com/54449993/72550943-13910900-3851-11ea-849a-5e93e240adf3.png">

**Comment by IonicaBizau** [comment]
That's probably because the HTML element is missing.

**Comment by 1sdc0d3r** [comment]
I see, I was trying to run the script before I had implemented the container. That was a simple problem I simply overlooked. Thank you very much. Great job on this library as well! Thank you.
