### ISSUE TITLE
The example (codepan) doesn't work - Loading the data just for you all the time 

### ISSUE THREAD

**Issue by hayorov** [IonicaBizau/github-calendar#97]
## Steps to reproduce:

- Follow the example link from README.md file https://codepen.io/anon/pen/aZmjvZ?editors=1000
- Open the browser windows
- The result on the screen:
![image](https://user-images.githubusercontent.com/991591/74405563-59e58200-4e68-11ea-89b9-7e1727303f74.png)

Developer console reports the next errors:
![image](https://user-images.githubusercontent.com/991591/74405629-84cfd600-4e68-11ea-9c9d-defeddffa06d.png)

Browsers: `Chrome 80.0.3987.87 (Official Build) (64-bit)` and `Firefox 72.0.2 (64-bit)` all on macOs  `11.15.3`

## Fix

- Change `https://cdn.rawgit.com/IonicaBizau/github-calendar/master/dist/github-calendar.min.js` to `https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js` fixes the problem.

**Comment by shaheemMPM** [comment]
change the src of script to https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js

**Comment by hayorov** [comment]
> change the src of script to https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js

@shaheemMPM ⬆️ Fix section, sometimes reading is worth it. 😏

**Comment by IonicaBizau** [comment]
We have to get rid of the `rawgit.com` links.

**Comment by hayorov** [comment]
Thank you @IonicaBizau
