### ISSUE TITLE
Summary columns don't fill space equally in the horizontal direction. 

### ISSUE THREAD

**Issue by jmccormac01** [IonicaBizau/github-calendar#98]
I've included the calendar on my basic website jamesjmccormac.com but the summary columns at the bottom of the calendar are shifted to the left. It would be nice if they were centered and took up 1/3rd each. I tried looking at the JS but it appears obfuscated. Any ideas?

![Screenshot 2020-03-05 17 16 27](https://user-images.githubusercontent.com/1912007/76006947-2cd73d00-5f05-11ea-8996-bdee16ce2f45.png)

**Comment by IonicaBizau** [comment]
Well, because the square container has a fixed width. You can fix it with CSS, but I think it's easier to keep everything fixed width.

**Comment by birkhofflee** [comment]
@IonicaBizau It's completely broken on mobile devices on my end :(
