### ISSUE TITLE
Fetch URL issue

### ISSUE THREAD

**Issue by abhishekds94** [IonicaBizau/github-calendar#99]
Access to fetch at 'https://urlreq.appspot.com/req?method=GET&url=https://github.com/users/IonicaBizau/contributions' from origin 'https://ionicabizau.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Getting the above error message from a couple of days. Could you please look into this?

**Comment by lrose07** [comment]
I'm getting the same, and grid is no longer showing. Has been working fine; this started happening sometime in the past week.

<img width="1440" alt="Screen Shot 2020-04-06 at 15 57 56" src="https://user-images.githubusercontent.com/5395968/78599620-7629ed80-781f-11ea-896e-2c9331537965.png">

**Comment by jKh98** [comment]
Same here. It was perfectly working for a while then since last week this error started appearing. I hope you'll find a solution soon and thanks for the amazing plugin.

**Comment by nikolas-ball** [comment]
Hello! Same issue here! I wonder what the fix is.

**Comment by IonicaBizau** [comment]
Does anyone recommend a good proxy service that has a good reputation? We could change the default proxy.

**Comment by mvpopuk** [comment]
Same problem here... I am just implementing this into my website and I just got the same error.

**Comment by denmercs** [comment]
same problem here. Hopefully, this will be resolved. Thanks!

**Comment by mvpopuk** [comment]
It seems like it's working now. Is it stable ? Can I use it in production ? Thanks.

**Comment by justinvforvendetta** [comment]
seems to be working again! we can close this issue @Abhishekds94

**Comment by justinvforvendetta** [comment]
and now its down again lol

**Comment by denmercs** [comment]
Yes it's down again... 😅

**Comment by abhishekds94** [comment]
> Yes it's down again... 😅

Ah, man.

Someone suggest to him a good proxy server so that he could use it without any interruption in the service.

**Comment by mvpopuk** [comment]
Any updates here ? I am supposed to launch a website in production today with this widget working. What should I do ? :)

**Comment by mvpopuk** [comment]
Working again :)

**Comment by IonicaBizau** [comment]
I'm on it. 🚀 Will add a `cache` option and a different proxy service, with the option to self-host it.

**Comment by mvpopuk** [comment]
Sould I consider using it in production now or should I wait a bit longer ? I'd also love to contribute to this repo since I like very much. If I can help in any ways please let me know. Noroc.

**Comment by IonicaBizau** [comment]
I hope I will release a new version in one hour.

Thank you, will consider that. Noroc! 😄

**Comment by justinvforvendetta** [comment]
thanks!
